"""
AWS KMS HSM Adapter for QASP v1.0.

This module provides an HSM implementation that integrates with AWS Key Management Service (KMS)
for secure key storage and cryptographic operations in production environments.

The adapter uses AWS KMS for:
- Secure key generation and storage
- Envelope encryption for data keys
- Cryptographic operations (sign/verify, encrypt/decrypt)
- Key rotation management

Security considerations:
- Keys never leave AWS KMS (except when encrypted)
- All operations are logged in CloudTrail
- Uses envelope encryption pattern for data protection
- Supports multi-tenant key isolation via key aliases

Prerequisites:
- AWS credentials configured (IAM role or access keys)
- KMS key created with appropriate permissions
- Environment variables: AWS_REGION, KMS_KEY_ID
"""

import logging
import os
import base64
from typing import Dict, List, Optional

try:
    import boto3
    from botocore.exceptions import ClientError, NoCredentialsError
    AWS_AVAILABLE = True
except ImportError:
    AWS_AVAILABLE = False
    boto3 = None

from ..abstract_store import KeyStoreABC

logger = logging.getLogger(__name__)


class AWSKMSAdapter(KeyStoreABC):
    """
    AWS KMS-based HSM adapter for production key management.

    This adapter provides secure key storage using AWS KMS for envelope encryption
    and cryptographic operations. All sensitive key material is protected by KMS.

    Security model:
    - Data encryption keys (DEKs) are generated by KMS and immediately encrypted
    - Key encryption keys (KEKs) are managed by KMS with proper access controls
    - Tenant isolation achieved through key aliases and IAM policies
    """

    def __init__(self):
        """Initialize AWS KMS adapter."""
        if not AWS_AVAILABLE:
            raise ImportError("boto3 is required for AWS KMS adapter. Install with: pip install boto3")

        self.region = os.getenv("AWS_REGION", "us-east-1")
        self.key_id = os.getenv("KMS_KEY_ID")

        if not self.key_id:
            raise ValueError("KMS_KEY_ID environment variable must be set for AWS KMS adapter")

        try:
            self.kms_client = boto3.client('kms', region_name=self.region)
            # Test connection
            self.kms_client.describe_key(KeyId=self.key_id)

            logger.info(
                "AWS KMS adapter initialized successfully",
                extra={
                    "aws_region": self.region,
                    "kms_key_id": self.key_id,
                    "security_event": "kms_adapter_init"
                }
            )

        except NoCredentialsError:
            raise ValueError("AWS credentials not found. Configure AWS credentials or IAM role.")

        except ClientError as e:
            if e.response['Error']['Code'] == 'NotFoundException':
                raise ValueError(f"KMS key {self.key_id} not found or not accessible")
            elif e.response['Error']['Code'] == 'AccessDeniedException':
                raise ValueError(f"Access denied to KMS key {self.key_id}")
            else:
                raise ValueError(f"AWS KMS error: {e}")

    def _get_tenant_key_alias(self, tenant_id: str, client_id: str, key_type: str) -> str:
        """Generate a unique key alias for tenant-scoped keys."""
        return f"alias/qasp/{tenant_id}/{client_id}/{key_type}"

    def _encrypt_data_key(self, data_key: bytes) -> Dict[str, str]:
        """
        Encrypt a data encryption key using AWS KMS.

        Args:
            data_key: The plaintext data key to encrypt

        Returns:
            Dictionary containing encrypted key and metadata
        """
        try:
            response = self.kms_client.encrypt(
                KeyId=self.key_id,
                Plaintext=data_key,
                EncryptionAlgorithm='SYMMETRIC_DEFAULT'
            )

            return {
                'encrypted_key': base64.b64encode(response['CiphertextBlob']).decode(),
                'key_id': response['KeyId'],
                'encryption_algorithm': response['EncryptionAlgorithm']
            }

        except ClientError as e:
            logger.error(f"Failed to encrypt data key with KMS: {e}")
            raise

    def _decrypt_data_key(self, encrypted_key_data: str) -> bytes:
        """
        Decrypt a data encryption key using AWS KMS.

        Args:
            encrypted_key_data: Base64-encoded encrypted key data

        Returns:
            The decrypted plaintext data key
        """
        try:
            encrypted_key = base64.b64decode(encrypted_key_data)

            response = self.kms_client.decrypt(
                CiphertextBlob=encrypted_key,
                EncryptionAlgorithm='SYMMETRIC_DEFAULT'
            )

            return response['Plaintext']

        except ClientError as e:
            logger.error(f"Failed to decrypt data key with KMS: {e}")
            raise

    def store_private_key(self, tenant_id: str, client_id: str, key_type: str, key_bytes: bytes) -> bool:
        """
        Store a private key encrypted with AWS KMS envelope encryption.

        The key is encrypted using a data encryption key (DEK) which is itself
        encrypted by AWS KMS. Both the encrypted data key and encrypted key data
        are stored in the database.

        Args:
            tenant_id: Unique identifier for the tenant
            client_id: Unique identifier for the client
            key_type: Type of key ('kem' or 'sign')
            key_bytes: The private key data as bytes

        Returns:
            True if storage was successful, False otherwise
        """
        try:
            # Generate a data encryption key from AWS KMS
            response = self.kms_client.generate_data_key(
                KeyId=self.key_id,
                KeySpec='AES_256',
                KeyUsage='ENCRYPT_DECRYPT'
            )

            data_key = response['Plaintext']  # Used for encryption
            encrypted_data_key = response['CiphertextBlob']  # Stored securely

            # Encrypt the private key with the data key (AES-GCM)
            from cryptography.hazmat.primitives.ciphers.aead import AESGCM
            aesgcm = AESGCM(data_key)

            nonce = os.urandom(12)
            encrypted_key_data = aesgcm.encrypt(nonce, key_bytes, None)

            # Store in database using our session
            from ...db.session import DatabaseSession
            from ...db.models import KeyRecord

            with DatabaseSession() as db:
                key_id = self._get_tenant_key_alias(tenant_id, client_id, key_type)

                # Remove 'alias/' prefix for database storage
                db_key_id = key_id.replace('alias/qasp/', '')

                key_record = KeyRecord(
                    tenant_id=tenant_id,
                    key_id=db_key_id,
                    key_type=key_type,
                    key_algorithm="AWS-KMS-AES256-GCM",
                    encrypted_key_data=base64.b64encode(encrypted_key_data).decode(),
                    key_nonce=nonce.hex(),
                    key_tag="",  # Not used with AES-GCM directly from KMS
                )
                db.add(key_record)

                # Also store the encrypted data key somewhere...
                # For now, we'll extend the model or use a separate table
                # This is a simplified approach - in production you'd have a separate
                # KMSDataKey table or extend KeyRecord

                # Store encrypted data key as metadata (this is simplified)
                key_record.key_metadata = base64.b64encode(encrypted_data_key).decode()

                db.commit()

            logger.info(
                f"Private key stored successfully in AWS KMS",
                extra={
                    "tenant_id": tenant_id,
                    "client_id": client_id,
                    "key_type": key_type,
                    "key_size": len(key_bytes),
                    "kms_key_id": self.key_id,
                    "security_event": "kms_key_storage"
                }
            )
            return True

        except Exception as e:
            logger.error(
                f"Failed to store private key with AWS KMS",
                extra={
                    "tenant_id": tenant_id,
                    "client_id": client_id,
                    "key_type": key_type,
                    "error": str(e),
                    "security_event": "kms_key_storage_failure"
                }
            )
            return False

    def get_private_key(self, tenant_id: str, client_id: str, key_type: str) -> Optional[bytes]:
        """
        Retrieve and decrypt a private key from AWS KMS.

        Args:
            tenant_id: Unique identifier for the tenant
            client_id: Unique identifier for the client
            key_type: Type of key ('kem' or 'sign')

        Returns:
            The decrypted private key bytes if found and decryption successful, None otherwise
        """
        try:
            from ...db.session import DatabaseSession
            from ...db.models import KeyRecord

            with DatabaseSession() as db:
                db_key_id = f"{tenant_id}/{client_id}/{key_type}"
                key_record = db.query(KeyRecord).filter_by(
                    tenant_id=tenant_id,
                    key_id=db_key_id,
                    is_active=True
                ).first()

                if not key_record or not key_record.key_metadata:
                    logger.warning(
                        f"Private key not found in AWS KMS",
                        extra={
                            "tenant_id": tenant_id,
                            "client_id": client_id,
                            "key_type": key_type,
                            "security_event": "kms_key_retrieval_not_found"
                        }
                    )
                    return None

                # Decrypt the data key using AWS KMS
                encrypted_data_key = base64.b64decode(key_record.key_metadata)
                data_key = self._decrypt_data_key(base64.b64encode(encrypted_data_key).decode())

                # Decrypt the private key using AES-GCM
                from cryptography.hazmat.primitives.ciphers.aead import AESGCM
                aesgcm = AESGCM(data_key)

                encrypted_key_data = base64.b64decode(key_record.encrypted_key_data)
                nonce = bytes.fromhex(key_record.key_nonce)

                decrypted_key = aesgcm.decrypt(nonce, encrypted_key_data, None)

                logger.info(
                    f"Private key retrieved successfully from AWS KMS",
                    extra={
                        "tenant_id": tenant_id,
                        "client_id": client_id,
                        "key_type": key_type,
                        "key_size": len(decrypted_key),
                        "security_event": "kms_key_retrieval"
                    }
                )
                return decrypted_key

        except Exception as e:
            logger.error(
                f"Failed to retrieve and decrypt private key from AWS KMS",
                extra={
                    "tenant_id": tenant_id,
                    "client_id": client_id,
                    "key_type": key_type,
                    "error": str(e),
                    "security_event": "kms_key_retrieval_failure"
                }
            )
            return None

    def list_keys(self, tenant_id: str) -> List[Dict[str, str]]:
        """
        List all stored keys for a given tenant in AWS KMS.

        Args:
            tenant_id: Unique identifier for the tenant

        Returns:
            List of dictionaries with key information
        """
        try:
            from ...db.session import DatabaseSession
            from ...db.models import KeyRecord

            keys = []
            with DatabaseSession() as db:
                key_records = db.query(KeyRecord).filter_by(
                    tenant_id=tenant_id,
                    is_active=True
                ).all()

                for record in key_records:
                    # Parse client_id and key_type from key_id
                    parts = record.key_id.split('/')
                    if len(parts) >= 3:
                        client_id, key_type = parts[1], parts[2]
                        keys.append({
                            "client_id": client_id,
                            "key_type": key_type,
                            "key_algorithm": record.key_algorithm,
                            "created_at": record.created_at.isoformat() if record.created_at else None
                        })

            logger.info(f"Key listing requested for tenant {tenant_id}: {len(keys)} keys found")
            return keys

        except Exception as e:
            logger.error(
                f"Failed to list keys for tenant {tenant_id}",
                extra={
                    "tenant_id": tenant_id,
                    "error": str(e),
                    "security_event": "kms_key_list_failure"
                }
            )
            return []

    def rotate_key(self, tenant_id: str, client_id: str, key_type: str) -> bool:
        """
        Rotate a key using AWS KMS automatic key rotation.

        Note: This adapter doesn't implement key rotation as AWS KMS handles
        key rotation automatically for symmetric keys. For asymmetric keys,
        rotation would require generating new key pairs.

        Args:
            tenant_id: Unique identifier for the tenant
            client_id: Unique identifier for the client
            key_type: Type of key to rotate

        Returns:
            False - rotation should be handled by AWS KMS or manual intervention
        """
        logger.warning(
            "AWS KMS adapter does not implement key rotation - use AWS KMS automatic rotation",
            extra={
                "tenant_id": tenant_id,
                "client_id": client_id,
                "key_type": key_type,
                "kms_key_id": self.key_id,
                "security_event": "kms_key_rotation_denied"
            }
        )
        return False

    def sign_data(self, tenant_id: str, client_id: str, key_type: str, data: bytes) -> Optional[bytes]:
        """
        Sign data using AWS KMS.

        Note: This is a placeholder for future implementation with asymmetric KMS keys.
        Current implementation uses envelope encryption approach only.

        Args:
            tenant_id: Unique identifier for the tenant
            client_id: Unique identifier for the client
            key_type: Type of key (must be asymmetric)
            data: Data to sign

        Returns:
            Signature bytes, or None if signing failed
        """
        logger.warning(
            "AWS KMS signing not implemented - use dedicated signing keys",
            extra={
                "tenant_id": tenant_id,
                "client_id": client_id,
                "key_type": key_type,
                "security_event": "kms_signing_not_implemented"
            }
        )
        return None
